### ISSUE TITLE
main.js is huge

### ISSUE THREAD

**Issue by taspeotis** [SteveF92/FantasyCritic#1]
I have a 100mbit connection and the page takes 10+ seconds to load. Either main.js needs to be smaller or your site needs to serve content faster.

![image](https://user-images.githubusercontent.com/1189399/50571580-f4683a80-0df9-11e9-9baf-9d981ea40ec4.png)

**Comment by SteveF92** [comment]
The most recent update turns minification of main.js back on. While I'm sure there's more I could do, this made the file about 50% as large.

**Comment by selangley** [comment]
While it would be some effort, an upgrade of the UI from Vue.js 2.x to 3.x would probably provide another level of size reduction.

https://v3-migration.vuejs.org/breaking-changes/global-api-treeshaking.html

> With global tree-shaking, the users only “pay” for the features they actually use. Even better, knowing that optional features won't increase the bundle size for applications not using them, framework size has become much less a concern for additional core features in the future, if at all.

https://en.wikipedia.org/wiki/Tree_shaking
> In computing, tree shaking is a dead code elimination technique that is applied when optimizing code.

**Comment by SteveF92** [comment]
I am thinking of switching to Vue 3, or perhaps Nuxt 3. No ETA on that though.
