### ISSUE TITLE
refresh tokens get bigger and bigger and bigger

### ISSUE THREAD

**Issue by drcatdoctor** [SteveF92/FantasyCritic#15]
Hi,

I've been working on [a bot](https://github.com/drcatdoctor/fcbot) and it turns out that if you are refreshing a refresh token over and over for weeks, it eventually looks like this: (decoded from base64):
`{"alg":"HS256","typ":"JWT"}{"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name":"***@***.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier":"****","nbf":1582606990,"exp":1582607890,"iss":"localhost","aud":["users","users","users","users","users","users","users","users","users","users","users","users","users","users","users","users","users","users","users","users","users","users","users", ...`

And it seems like there's a new "users" added every refresh. Eventually the "aud" list got so long that I started getting HTTP 400 Client Errors because the authorization header was too long for HTTP.

So, the problem starts here:
https://github.com/SteveF92/FantasyCritic/blob/71e512e949eafa73d9612843faaae4665cb4b252/FantasyCritic.Web/Controllers/API/TokenController.cs#L64

The `principal` there is coming from:
https://github.com/SteveF92/FantasyCritic/blob/71e512e949eafa73d9612843faaae4665cb4b252/FantasyCritic.Web/Controllers/API/TokenController.cs#L36

And (as the requester) I already have an audience in my claims...

When TokenService generates the access token, it calls:
https://github.com/SteveF92/FantasyCritic/blob/71e512e949eafa73d9612843faaae4665cb4b252/FantasyCritic.Web/Services/TokenService.cs#L32-L38

And [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtsecuritytoken.-ctor?view=azure-dotnet#System_IdentityModel_Tokens_Jwt_JwtSecurityToken__ctor_System_String_System_String_System_Collections_Generic_IEnumerable_System_Security_Claims_Claim__System_Nullable_System_DateTime__System_Nullable_System_DateTime__Microsoft_IdentityModel_Tokens_SigningCredentials_) for that constructor says:

`claims IEnumerable<Claim>`
"If this value is not null then for each Claim a { 'Claim.Type', 'Claim.Value' } is added. If duplicate claims are found then a { 'Claim.Type', List<object> } will be created to contain the duplicate values."

What it doesn't say is that according to [the RFC for JWTs](https://tools.ietf.org/html/rfc7519#section-4.1.3), all the other claim types can't be lists, except for "aud", so internally the JwtSecurityToken class must be discarding all the other duplicates, and the only thing it does is add "users" another time to the "aud" list. And over and over and over.

I see this is exactly the way it's done in a bunch of tutorials, so I think the problem is the documentation. I opened an issue in the Microsoft repository.

I think a fix for this could be to add a `List<Claim> GetUserClaims(FantasyCriticUser user)` to UserManager, and use it in `AccountController.GetToken` and `TokenController.Refresh` instead of `principal.Claims`. But I can't test it out because I don't have a C# dev environment.

**Comment by SteveF92** [comment]
I just pushed up a change that hopefully fixes this. I'll be honest, I didn't test it extensively because I didn't try to reproduce the original issue, I just took your idea for a solution.

Can you try and see if they problem is resolved?

**Comment by drcatdoctor** [comment]
Looks like it did work! I can see at 6:03 am GMT that day, there was a refresh and it had a super long response, then 6:24am there was a refresh and it was much shorter. Thanks!

It was kind of fascinating to look into, it was a very weird thing to see and I've never made anything before that uses refresh tokens for so long, so I had to make sure it wasn't me screwing up or a library I was using.

**Comment by drcatdoctor** [comment]
Closing due to fix in commit a3ec0c5.
