### ISSUE TITLE
Cannot create and account on the site

### ISSUE THREAD

**Issue by caleb902** [SteveF92/FantasyCritic#2]
When I hit sign up nothing happens, as if the button does not work. What am I doing wrong here?

**Comment by SteveF92** [comment]
I'm going to need more information. Message me privately if you don't want your sign in info public. A screenshot would be great, and the developer console messages would be even better. For the second one, press F12 before you click "sign up", and see if you get any errors in the console.

**Comment by caleb902** [comment]
![image](https://user-images.githubusercontent.com/47604593/52731297-c139cf00-2f93-11e9-8065-fa7df0cbc12c.png)


This is what I'm getting. When I click sign in it simply just wont do anything.

**Comment by SteveF92** [comment]
According to my records there is already an account with that email. Use the "forgot password" feature if you need it.

**Comment by caleb902** [comment]
Here it is on chrome 
![image](https://user-images.githubusercontent.com/47604593/52731557-5b9a1280-2f94-11e9-8efd-d923b761e9c0.png)

**Comment by SteveF92** [comment]
I can and will add a message that says "An account already exists with that email" though.

**Comment by caleb902** [comment]
Perfect, my apologies!
