### ISSUE TITLE
Error 500 when trying to add a game in draft

### ISSUE THREAD

**Issue by colletes** [SteveF92/FantasyCritic#26]
When we try to add a game in our draft, site returns error 500 and gets stuck on "add game to publisher" screen.
![image](https://user-images.githubusercontent.com/73607132/97471824-e1f0b680-1927-11eb-8b6a-5c72cf0a57dd.png)

**Comment by SteveF92** [comment]
I forgot to change the "add new game" code to account for the new field that handles manual "will not release" status. I just pushed up a change that fixes this.
