### ISSUE TITLE
Drop modal is missing "confirm drop" button in safari browser when a game has not been dropped first time

### ISSUE THREAD

**Issue by PaulACoroneos** [SteveF92/FantasyCritic#30]
## Expected

Drop game modal should have a button to confirm selection of dropping a game in safari browsers (iPhone and Mac OS) when a game has not been dropped in first place.

## Actual

Button is missing for safari browsers.

## Repro steps

1) Under player actions select "drop a game"
2) Select any game in select element. 
3) Observe no button is present to submit selection for first drop attempt

## Workaround

I was able to work around this by using Firefox (or chrome browser) and completing drop there. After first drop safari browser behavior now works as expected.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/40515238/113492035-bb1c4a80-949a-11eb-9279-12b0adbf9301.png">

**Comment by SteveF92** [comment]
Unfortunately at this time I don't have the ability to test with Safari. I will change that at some point, but in the meantime, I would accept a PR to fix this.

**Comment by PaulACoroneos** [comment]
I can see if during my vacation from work this holiday I can assist you to tackle some of the safari issues. Appreciate the work you’ve done on the site.

**Comment by PaulACoroneos** [comment]
This appears to be working as expected now. Closing.
