### ISSUE TITLE
Login/logout text leaks out of button in mobile safari

### ISSUE THREAD

**Issue by PaulACoroneos** [SteveF92/FantasyCritic#31]
The login/logout text leak outside of the buttons in header in safari browser (testing device iPhone 12 Pro iOS12)

![IMG_3064](https://user-images.githubusercontent.com/40515238/113492519-82ca3b80-949d-11eb-803e-2a83cab5e6cb.jpeg)

**Comment by SteveF92** [comment]
Unfortunately at this time I don't have the ability to test with Safari. I will change that at some point, but in the meantime, I would accept a PR to fix this.

**Comment by PaulACoroneos** [comment]
Looks like this is resolved per testing on my iPhone. Closing.
