### ISSUE TITLE
Edit Publishers Bugged

### ISSUE THREAD

**Issue by Aevaro** [SteveF92/FantasyCritic#39]
When I go to edit a publisher to change their current budget left and the number of the games they have to drop, it will let me enter new values but when I go to click the Edit Publisher button nothing happens. When I make no changes and click Edit Publisher it does note that a change needs to be made.

**Comment by SteveF92** [comment]
Sorry it took me so long to address this. I can't reproduce it though. Is it still happening?

**Comment by Aevaro** [comment]
Tested it again. It looks like if I try to change a person's remaining budget or "will not release game drops" one at a time it works fine but if I try to change both values the Edit Publisher button doesn't do anything when clicked.

**Comment by SteveF92** [comment]
Sorry I've been slow on this. I believe I just fixed it though. Let me know.
