### ISSUE TITLE
Cannot access my account

### ISSUE THREAD

**Issue by 0Gundam** [SteveF92/FantasyCritic#45]
Two days after creating my account I attempted to login and was prompted with invalid login. I'm 99% sure I'm using the correct email and password I created. Nevertheless I pressed forgot password and after entering the correct email for the account I was never sent a link to reset password. Any help with this would be greatly appreciated.

**Comment by SteveF92** [comment]
Sorry I never addressed this. I imagine this is fixed by now, but if it isn't, message me on Discord or Twitter.
