### ISSUE TITLE
Question: $http Vue instance property

### ISSUE THREAD

**Issue by AndrewKralovec** [SteveF92/FantasyCritic#6]
I saw in app.js, that axois was added as an Vue instance property, `$http`. However, in many of the Vue components, axois used by importing the package. In fact, i don't see `$http` used anywhere in the client app. Is there a reason to assign axois as as an instance property, when it appears to not be used? 

```javascript 
// Registration of global components
Vue.component('font-awesome-icon', FontAwesomeIcon);
Vue.component('font-awesome-layers', FontAwesomeLayers);
Vue.component('font-awesome-layers-text', FontAwesomeLayersText);
Vue.prototype.$http = axios;
sync(store, router);
```

**Comment by SteveF92** [comment]
I suppose you're right. To be honest I think I took it from the template I used without thinking about it. I should be able to remove that line

**Comment by AndrewKralovec** [comment]
@SteveF92 , or update the components to use `$http`, instead. There should be no performance impact. I think its preference, do you like importing axois for each component, or would you rather use a property.
