### ISSUE TITLE
"Someone in league already has this" filter 

### ISSUE THREAD

**Issue by MorkaiAU** [SteveF92/FantasyCritic#63]
Is it possible, when searching through the master game list, to add a checkbox/filter for "someone in my league already has this".

There's already a filter for "show unreleased games" but I believe it would be good to be able to filter out things that have already been bid upon and picked up by another league member.

Thanks!

**Comment by SteveF92** [comment]
This is a feature for Patreon supporters already:

https://www.fantasycritic.games/fantasyCriticPlus


Sorry I didn't respond to this sooner.
