### ISSUE TITLE
[Feature] Table filter for games table

### ISSUE THREAD

**Issue by AndrewKralovec** [SteveF92/FantasyCritic#7]
Would table filtering options be desirable for the games table ? Adding a filter for game names was pretty easy to do. 

I did notice, due to the large amount of data, that filtering did produce a lag when the filter input was less then 3 characters.  Adding pagination dramatically reduced this, but then games not in the current page view would not be fulled up from the game name filtering. 
Note, not relying off of vue-bootstrap to filter the table, (IE computed property to filter included strings) was twice as fast. 

https://github.com/AndrewKralovec/FantasyCritic/tree/GameTableFiltering

**Comment by SteveF92** [comment]
Can you show me a screenshot of the final product? I'm definitely interested.

**Comment by AndrewKralovec** [comment]
As you can see its pretty slow to start. I would want to speed up the filter before adding it to master. 

https://gifyu.com/image/hY8g

**Comment by SteveF92** [comment]
Hey I sent you an email. Can you respond there?

**Comment by AndrewKralovec** [comment]
@SteveF92 , So i was playing around with how to speed this up. Those attempts were not 'desirable', but I have alternatives (see below).  I suspect the lag is coming from the re-rendering of the bootstrap table components. Maybe its best to just close this feature out and re-visit it if necessary. 


Lazy
Use the lazy modifier to sync the input on change. This is better, but still noticeable lag.
```
<b-form-input 
  v-model.lazy="filter"
  type="search" 
  id="filterInput" 
  placeholder="Search by game name"
></b-form-input>
```
Debounce
Use loadash (there are others if need be as well) to debounce the user input. This has been the smoothest experience. The user will only experience a small lag when completely clearing out the input.

```
<b-form-input 
  @input="updateInput"
  placeholder="Search by game name"
></b-form-input>
...

updateInput: debounce(function (value) {
  this.filter = value
}, 300)
```

Filter ending string
Since the lag is coming from the large data set of matching values,  only filter after the input reaches 3 chars. Filtering by the first two chars, will results in almost every game name. I don't really like this solution, however. Most is not all.
