### ISSUE TITLE
Feature Request: Allow users to move games into slots that they are not eligible for

### ISSUE THREAD

**Issue by nturinski** [SteveF92/FantasyCritic#71]
Hi there, first off, just wanted to say that I love this project and thank you so much for doing it.

I was hoping that I could request that you revert the following change:
> They intentionally moved a game into a slot it's not eligble for. This used to be possible but no longer is.

I get that this is a QoL change, but our league are using two `DC` tagged slots as a "bench". The idea is that these games do not count for any points, but you are still able to reserve them. This was primarily intended to be used as a way to not punish players for bidding on riskier options or to collect games that could be used for trading.

However, by removing the ability the intentionally move games into ineligible slots, this "bench feature" workaround doesn't work anymore. Is there anyway that this limitation could be reverted?

Thanks!

**Comment by SteveF92** [comment]
Sorry I haven't responded to this. I should have seen this sooner but didn't. I will add this as an opt in option. By default, it will not be allowed.

**Comment by SteveF92** [comment]
This is done now, you can find it in "Change Year-Specific Options"->"Advanced Settings"

**Comment by nturinski** [comment]
Thanks so much @SteveF92
